question_data =[
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "George Lucas directed the entire original Star Wars trilogy.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Actor Tommy Chong served prison time.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
